language: node_js

node_js:
  - node
  - lts/*

cache: npm

jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: npm release
      node_js: node
      script:
        - npm run build:clean
        - npm run build:npm
      deploy:
        edge: true
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        on:
          branch: master
          tags: true
