language: node_js

node_js:
  - node
  - lts/*

cache: npm

jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: deploy
      node_js: node
      email: "$NPM_EMAIL"
      api_key: "$NPM_TOKEN"
      script:
        - npm run build:clean
        - npm run build:npm
        - npm publish
      on:
        branch: master
        tags: true
