language: node_js

node_js:
  - node
  - lts/*

cache: npm

jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: deploy
      node_js: node
      script:
        - npm run build:clean
        - npm run build:npm
        - npm publish

deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"
  on:
    branch: master
    tags: true
